/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./script.js"],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "tertiary-fixed-dim": "#b190ff",
              "surface": "#0e0e0e",
              "surface-tint": "#81ecff",
              "primary": "#81ecff",
              "outline-variant": "#484847",
              "error-dim": "#d7383b",
              "on-primary-fixed": "#003840",
              "tertiary": "#ac89ff",
              "on-secondary-container": "#fff5fc",
              "surface-container-low": "#131313",
              "secondary-fixed": "#f1c1ff",
              "on-primary-fixed-variant": "#005762",
              "surface-container-lowest": "#000000",
              "surface-container": "#1a1a1a",
              "on-tertiary-fixed": "#1f0052",
              "on-surface-variant": "#adaaaa",
              "on-primary-container": "#004d57",
              "secondary-fixed-dim": "#eaaeff",
              "on-tertiary": "#290067",
              "surface-bright": "#2c2c2c",
              "inverse-on-surface": "#565555",
              "on-tertiary-container": "#f8f1ff",
              "tertiary-fixed": "#bda1ff",
              "background": "#0e0e0e",
              "inverse-surface": "#fcf9f8",
              "surface-variant": "#262626",
              "on-secondary-fixed": "#580079",
              "error-container": "#9f0519",
              "primary-container": "#00e3fd",
              "on-secondary": "#390050",
              "primary-fixed-dim": "#00d4ec",
              "secondary-dim": "#bb00fc",
              "tertiary-dim": "#874cff",
              "on-secondary-fixed-variant": "#8400b3",
              "on-surface": "#ffffff",
              "secondary": "#d674ff",
              "outline": "#767575",
              "surface-dim": "#0e0e0e",
              "secondary-container": "#9900cf",
              "on-tertiary-fixed-variant": "#4700a7",
              "surface-container-high": "#20201f",
              "surface-container-highest": "#262626",
              "tertiary-container": "#7000ff",
              "on-primary": "#005762",
              "inverse-primary": "#006976",
              "on-error": "#490006",
              "on-background": "#ffffff",
              "on-error-container": "#ffa8a3",
              "error": "#ff716c",
              "primary-dim": "#00d4ec",
              "primary-fixed": "#00e3fd"
          },
          "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
          },
          keyframes: {
              'hero-fade': {
                  '0%': { opacity: '0', transform: 'translateY(2rem)' },
                  '100%': { opacity: '1', transform: 'translateY(0)' },
              }
          },
          animation: {
              'hero': 'hero-fade 0.8s ease-out forwards',
          }
      },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
