/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./js/**/*.js"],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "tertiary-fixed-dim": "#b3b3b3",
              "surface": "#0a0a0a",
              "surface-tint": "#ffffff",
              "primary": "#ffffff",
              "outline-variant": "#333333",
              "error-dim": "#d7383b",
              "on-primary-fixed": "#000000",
              "tertiary": "#cccccc",
              "on-secondary-container": "#ffffff",
              "surface-container-low": "#111111",
              "secondary-fixed": "#e6e6e6",
              "on-primary-fixed-variant": "#005762",
              "surface-container-lowest": "#000000",
              "surface-container": "#1a1a1a",
              "on-tertiary-fixed": "#1f0052",
              "on-surface-variant": "#adaaaa",
              "on-primary-container": "#004d57",
              "secondary-fixed-dim": "#eaaeff",
              "on-tertiary": "#290067",
              "surface-bright": "#2c2c2c",
              "inverse-on-surface": "#565555",
              "on-tertiary-container": "#f8f1ff",
              "tertiary-fixed": "#bda1ff",
              "background": "#0e0e0e",
              "inverse-surface": "#fcf9f8",
              "surface-variant": "#262626",
              "on-secondary-fixed": "#580079",
              "error-container": "#9f0519",
              "primary-container": "#1a1a1a",
              "on-secondary": "#000000",
              "primary-fixed-dim": "#cccccc",
              "secondary-dim": "#999999",
              "on-secondary-fixed-variant": "#333333",
              "on-surface": "#ffffff",
              "secondary": "#a6a6a6",
              "outline": "#404040",
              "surface-dim": "#050505",
              "secondary-container": "#262626",
              "on-tertiary-fixed-variant": "#4700a7",
              "surface-container-high": "#20201f",
              "surface-container-highest": "#262626",
              "tertiary-container": "#7000ff",
              "on-primary": "#005762",
              "inverse-primary": "#006976",
              "on-error": "#490006",
              "on-background": "#ffffff",
              "on-error-container": "#ffa8a3",
              "error": "#ff716c",
              "primary-dim": "#cccccc",
              "primary-fixed": "#ffffff"
          },
          "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
          },
          keyframes: {
              'hero-fade': {
                  '0%': { opacity: '0' },
                  '100%': { opacity: '1' },
              }
          },
          animation: {
              'hero': 'hero-fade 0.4s ease-out forwards',
          }
      },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
